### ISSUE TITLE
Readme's example print nothing

### ISSUE THREAD

**Issue by willbasky** [tweag/timestats#2]
**Describe the bug**
I tried an example from README. It hangs a while and prints nothing. 

**To Reproduce**
Run
```haskell
import Control.Exception (evaluate)
import qualified Debug.TimeStats as TimeStats (printTimeStats, measureM)

fib n = if n < 2 then 1 else fib (n - 1) + fib (n - 2)

main = do
    -- measureM collects the time taken to compute the given action
    -- and stores it associated with a given label in global state.
    TimeStats.measureM "fib" $ evaluate (fib 31)
    -- measuring multiple times with the same label adds up
    -- the time taken by all of those invocations
    TimeStats.measureM "fib2" $ evaluate (fib 30)
    -- adds up to the existing "fib2" stats
    TimeStats.measureM "fib2" $ evaluate (fib 29)
    TimeStats.printTimeStats
```

**Expected behavior**
It prints measurements

**Environment**
 - OS name + version: last Manjaro
 - Version of the code: ghc 9.0.2, and last stack version.

**Additional context**

**Comment by facundominguez** [comment]
Thanks @willbasky. I don't know yet how you are invoking your program. Therefore, I need to ask: Have you tried running your program with `DEBUG_TIMESTATS_ENABLE=1 ./program`?

**Comment by facundominguez** [comment]
> DEBUG_TIMESTATS_ENABLE=1 ./program

If this is the issue, it wouldn't harm being more explicit in the README about how to do the invocation. :thinking:

**Comment by willbasky** [comment]
Oh, with the envvar it works. Thanks :)
```haskell
❯ export DEBUG_TIMESTATS_ENABLE=1 && stack run
 fib: 0.060s  count: 1
fib2: 0.066s  count: 2
```
