### ISSUE TITLE
Add a thousands separator "," for counts

### ISSUE THREAD

**Issue by DaveBarton** [tweag/timestats#3]
Your tool is much faster and more lightweight than recompiling an entire project for GHC's profiler, so thanks!!

However, large counts would be much more readable to me if they had a thousands separator.

If necessary, this could be an option.

**Comment by facundominguez** [comment]
Thanks for the suggestion, @DaveBarton! Thus #4 work for you?

**Comment by DaveBarton** [comment]
I love it! Two small suggestions:

1. Maybe formatIntWithSeparator should work for negative Ints, or else be renamed a bit?

2. Maybe use ',' not '_' for the separator? For instance, +RTS -s produces output like:
```
 181,753,555,880 bytes allocated in the heap
   5,200,010,184 bytes copied during GC
      22,322,016 bytes maximum residency (15 sample(s))
         274,352 bytes maximum slop
```
This output is unlikely to be piped into another program or turned into Haskell source code, and it's just more readable I think with commas. Just my opinion, I'm happy either way.

Thanks again!

**Comment by facundominguez** [comment]
> Maybe formatIntWithSeparator should work for negative Ints

:+1: I implemented this one.

For now, I stick to using `_` as separator since comma is used sometimes as decimal separator (not in your cited case, of course).
